spring:
  application:
    name: TheBagPortal
  main:
    allow-bean-definition-overriding: true
  datasource: 
      url: jdbc:mysql://localhost:3306/thebags2208
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
